name: oxide-digitalsignage
version: 1
summary: Digital Signage Demo
description: Digital Signage based on Oxide WebView
confinement: strict

apps:
    start-oxide:
        command: start-oxide
        plugs: [browser-support, opengl, network, network-bind, x11]

parts:
    oxide:
        plugin: nil
        stage-packages:
            - liboxideqt-qmlplugin
            - qmlscene
            - qt5-default
            - qtchooser
            - qtbase5-dev
            - qtdeclarative5-ubuntu-ui-toolkit-plugin
            - libraspberrypi0
            - qtdeclarative5-dev
        filesets:
            unwanted:
                - -usr/lib/arm-linux-gnueabihf/libQt5*.so* 
                - -usr/lib/arm-linux-gnueabihf/qt5/
                - -usr/lib/arm-linux-gnueabihf/mesa-egl/
                stage: 
                    - $unwanted
    prebuilt:
        plugin: tar-content
        source: https://github.com/penk/oxide-eglfs-snap/releases/download/beta/prebuilt-qt5-armhf.tgz
        destination: ./usr/lib/arm-linux-gnueabihf/
    common:
        plugin: dump
        source: data
